---

jobs:
  release-please:
    outputs:
      release_created: "${{ steps.release.outputs.release_created }}"
      tag_name: "${{ steps.release.outputs.tag_name }}"
      version_number: "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
    runs-on: "ubuntu-latest"
    steps:
      - id: "release"
        uses: "googleapis/release-please-action@v4"

  releases:
    if: "${{ needs.release-please.outputs.release_created }}"
    needs:
      - "release-please"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "ruby/setup-ruby@v1"
        with:
          bundler-cache: true
      - env:
          RUBYGEMS_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"
        name: "Setup Access to rubygems.org Registry"
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 600 $HOME/.gem/credentials
          echo "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}" >> $HOME/.gem/credentials
      - name: "Build Rubygem"
        run: "gem build rapporteur.gemspec"
      - env:
          BINARY_NAME: "rapporteur-${{ needs.release-please.outputs.version_number }}.gem"
        name: "Push Rubygem"
        run: 'gem push "$BINARY_NAME"'
      - env:
          BINARY_NAME: "rapporteur-${{ needs.release-please.outputs.version_number }}.gem"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        name: "Upload Release Artifact"
        run: 'gh release upload ${{ needs.release-please.outputs.tag_name }} "$BINARY_NAME"'

name: "Release Please"

"on":
  push:
    branches:
      - "main"

permissions:
  contents: "write"
  pull-requests: "write"
